/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Robin
 */
import javax.swing.JOptionPane;

public class NewJDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public NewJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        theJFrame = (NewJFrame) parent;  // Store the ref value for the jFrame

    }

    public NewJFrame theJFrame;  // This holds the rev value for the jFrame in use.

    public void setTextFieldModify(EmployeeInfo empInfo) {

        //Set format
        
        m_FN.setText("");
        m_LN.setText("");
        m_EN.setText("");
        m_DR.setText("");
        m_S.setText("");
        m_HPW.setText("");
        m_WPY.setText("");

        // Display info of the employee that is been modified
        m_FN.setText(empInfo.getFirstName());
        m_LN.setText(empInfo.getLastName());
        m_EN.setText(Integer.toString(empInfo.getEmployeeNumber()));
        m_DR.setText(Double.toString(empInfo.getDeductionsRate()));
        if (empInfo instanceof FullTimeEmployee) {
            m_FT.setSelected(true);
            m_PT.setSelected(false);
            m_S.setVisible(true);
            m_HPW.setVisible(false);
            m_WPY.setVisible(false);
            jLabel5.setVisible(true);
            jLabel5.setText("Salary:");
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);

            m_S.setText(Double.toString(((FullTimeEmployee) empInfo).getSalary()));

        } else if (empInfo instanceof PartTimeEmployee) {
            m_PT.setSelected(true);
            m_FT.setSelected(false);

            m_S.setVisible(true);
            m_HPW.setVisible(true);
            m_WPY.setVisible(true);
            jLabel5.setVisible(true);
            jLabel5.setText("Hourly Wage:");
            jLabel6.setVisible(true);
            jLabel7.setVisible(true);

            m_S.setText(Double.toString(((PartTimeEmployee) empInfo).getHourlyWage()));
            m_HPW.setText(Double.toString(((PartTimeEmployee) empInfo).getHoursPerWeek()));
            m_WPY.setText(Double.toString(((PartTimeEmployee) empInfo).getWeeksPerYear()));

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        m_FN = new javax.swing.JTextField();
        m_LN = new javax.swing.JTextField();
        m_EN = new javax.swing.JTextField();
        m_DR = new javax.swing.JTextField();
        m_S = new javax.swing.JTextField();
        m_HPW = new javax.swing.JTextField();
        m_WPY = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        m_FT = new javax.swing.JCheckBox();
        m_PT = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modify Employee");

        jButton1.setText("Modify");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        m_FN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_FNActionPerformed(evt);
            }
        });

        m_LN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_LNActionPerformed(evt);
            }
        });

        m_EN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ENActionPerformed(evt);
            }
        });

        m_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_SActionPerformed(evt);
            }
        });

        m_HPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_HPWActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("Employee #:");

        jLabel4.setText("Deduction Rate:");

        jLabel5.setText("Hourly Wage:");

        jLabel6.setText("Hrs. Per Week:");

        jLabel7.setText("Weeks Per Yr.:");

        m_FT.setText("Full-Time");
        m_FT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_FTActionPerformed(evt);
            }
        });

        m_PT.setText("Part-Time");
        m_PT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_PTActionPerformed(evt);
            }
        });

        jLabel8.setText("Full/Part Time:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m_WPY, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m_HPW, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m_S, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m_DR, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m_EN, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m_LN, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m_FN, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(m_FT)
                                .addGap(18, 18, 18)
                                .addComponent(m_PT)
                                .addGap(11, 11, 11)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_FN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_LN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_EN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_DR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_FT)
                    .addComponent(m_PT)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_HPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_WPY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void m_ENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ENActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_ENActionPerformed

    private void m_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_SActionPerformed

    private void m_HPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_HPWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_HPWActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*
        if (m_PT.isSelected() == true) {
            
            theJFrame.addPartTime(m_EN.getText(), m_FN.getText(), m_LN.getText(), m_DR.getText(), m_S.getText(), m_HPW.getText(), m_WPY.getText());
            if (theJFrame.getadded() == true) {
                theJFrame.getMyHashTable().removeFromTable(theJFrame.getTempEmpNum());
            } else {
            }
        } else if (m_FT.isSelected() == true) {
            theJFrame.addFullTime(m_EN.getText(), m_FN.getText(), m_LN.getText(), m_DR.getText(), m_S.getText());
            if (theJFrame.getadded() == true) {
                theJFrame.getMyHashTable().removeFromTable(theJFrame.getTempEmpNum());
            } else {

            }
        } else {
            JOptionPane.showMessageDialog(null, "check modifications");
        }

        theJFrame.setDisplayTable(theJFrame.getMyHashTable().getArrayList());

        dispose();
         */

        
        //Modify the employee
        if ("".equals(m_FN.getText()) || m_LN.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "insufficent input ");
        } //        myEmployee = new EmployeeInfo(Integer.parseInt(add_EN.getText()), add_FN.getText(), add_LN.getText(), Double.parseDouble(add_DR.getText()));
        else if (m_PT.isSelected() == true) {
            try {

                //addPartTime(Integer.parseInt(add_EN.getText()), add_FN.getText(), add_LN.getText(), Double.parseDouble(add_DR.getText()), Double.parseDouble(add_S.getText()), Double.parseDouble(add_HPW.getText()), Double.parseDouble(add_WPY.getText()));
                if (theJFrame.getTempEmpNum() != Integer.parseInt(m_EN.getText()) && theJFrame.getMyHashTable().searchTable(Integer.parseInt(m_EN.getText())) != -1) {
                    JOptionPane.showMessageDialog(null, "You cannot use the same employee number twice.");
                } else {
                    theJFrame.addPartTime(m_EN.getText(), m_FN.getText(), m_LN.getText(), m_DR.getText(), m_S.getText(), m_HPW.getText(), m_WPY.getText());
                    if (theJFrame.getadded() == true) { //If added successfully then delete the old entry
                        theJFrame.getMyHashTable().removeFromTable(theJFrame.getTempEmpNum());
                        theJFrame.setDisplayTable(theJFrame.getMyHashTable().getArrayList());
                        dispose();//Close the window
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please input a number");
            }

            //safeGuard(1, 1);
        } else if (m_FT.isSelected() == true) {
            try {
                if (theJFrame.getTempEmpNum() != Integer.parseInt(m_EN.getText()) && theJFrame.getMyHashTable().searchTable(Integer.parseInt(m_EN.getText())) != -1) {
                    JOptionPane.showMessageDialog(null, "You cannot use the same employee number twice.");
                } else {
                    theJFrame.addFullTime(m_EN.getText(), m_FN.getText(), m_LN.getText(), m_DR.getText(), m_S.getText());
                    if (theJFrame.getadded() == true) {
                        theJFrame.getMyHashTable().removeFromTable(theJFrame.getTempEmpNum());
                        theJFrame.setDisplayTable(theJFrame.getMyHashTable().getArrayList());
                        dispose();
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please input a number");
            }
            //safeGuard(2, 1);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a checkbox");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void m_FNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_FNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_FNActionPerformed

    private void m_LNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_LNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_LNActionPerformed

    private void m_FTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_FTActionPerformed
        // TODO add your handling code here:
        m_PT.setSelected(false);
        m_S.setVisible(true);
        m_HPW.setVisible(false);
        m_WPY.setVisible(false);
        jLabel5.setVisible(true);
        jLabel5.setText("Salary:");
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);

        if (m_FT.isSelected() == false) {
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            m_S.setVisible(false);
            m_HPW.setVisible(false);
            m_WPY.setVisible(false);
        }
    }//GEN-LAST:event_m_FTActionPerformed

    private void m_PTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_PTActionPerformed
        m_FT.setSelected(false);
        m_S.setVisible(true);
        m_HPW.setVisible(true);
        m_WPY.setVisible(true);
        jLabel5.setVisible(true);
        jLabel5.setText("Hourly Wage:");
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);

        if (m_PT.isSelected() == false) {
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            m_S.setVisible(false);
            m_HPW.setVisible(false);
            m_WPY.setVisible(false);
        }    }//GEN-LAST:event_m_PTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialog dialog = new NewJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField m_DR;
    private javax.swing.JTextField m_EN;
    private javax.swing.JTextField m_FN;
    private javax.swing.JCheckBox m_FT;
    private javax.swing.JTextField m_HPW;
    private javax.swing.JTextField m_LN;
    private javax.swing.JCheckBox m_PT;
    private javax.swing.JTextField m_S;
    private javax.swing.JTextField m_WPY;
    // End of variables declaration//GEN-END:variables
}
